trigger:
- main

variables:
  ADMINSERVICE_MYSQL_MASTER_HOST: localhost
  ADMINSERVICE_MYSQL_REPLICA_HOST: localhost
  ADMINSERVICE_MYSQL_MASTER_PORT: 3306
  ADMINSERVICE_MYSQL_REPLICA_PORT: 3306
  MYSQL_USER: root
  MYSQL_PASS: imad
  RABBIT_HOST: localhost

pool:
  vmImage: ubuntu-latest

steps:
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'DockerRegistry'
    dockerComposeFile: 'docker/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'

- task: CmdLine@2
  inputs:
    script: 'until ping localhost:15672; do sleep 1; done'

- task: Maven@3
  inputs:
    mavenPomFile: 'adminservice/pom.xml'
    goals: 'clean install sonar:sonar'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerRegistry'
    repository: 'imadelfetouh99/adminservice'
    command: 'buildAndPush'
    Dockerfile: 'docker/Dockerfile'
    buildContext: 
    tags: 'latest'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'kube_kwetterimad'
    manifests: 'kubernetes/adminservice.yaml'

